import { useEffect, useState } from 'react'
import { NavLink, Navigate } from 'react-router-dom'
import useWindowTitle from '../../hooks/useWindowTitle'
import { usePermission } from '../../hooks/usePermission'
import { actuaryService } from '../../services/actuaryService'
import { fmt } from '../../utils/formatting'

const POSITION_STYLES = {
  SUPERVISOR: 'bg-violet-100 text-violet-700 dark:bg-violet-600/20 dark:text-violet-300',
  AGENT:      'bg-blue-100 text-blue-700 dark:bg-blue-600/20 dark:text-blue-300',
  ADMIN:      'bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-300',
}

export default function BankProfitActuariesPage() {
  useWindowTitle('Actuary Performances | AnkaBanka')
  const { can } = usePermission()

  if (!can('isSupervisor')) return <Navigate to="/" replace />

  const [performances, setPerformances] = useState([])
  const [loading,      setLoading]      = useState(true)
  const [error,        setError]        = useState(false)
  const [sortAsc,      setSortAsc]      = useState(false)

  useEffect(() => {
    actuaryService.getActuaryPerformances()
      .then(data => setPerformances(data))
      .catch(() => setError(true))
      .finally(() => setLoading(false))
  }, [])

  const sorted = [...performances].sort((a, b) =>
    sortAsc ? a.profit - b.profit : b.profit - a.profit
  )

  const tabClass = ({ isActive }) =>
    `px-5 py-2.5 text-xs tracking-widest uppercase font-medium border-b-2 transition-colors ${
      isActive
        ? 'border-violet-500 text-violet-700 dark:text-violet-300'
        : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200'
    }`

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 px-6 py-16">
      <div className="max-w-5xl mx-auto">

        <p className="text-xs tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-4">Bank Profit</p>
        <h1 className="font-serif text-4xl font-light text-slate-900 dark:text-white mb-1">Actuary Performances</h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 font-light mb-3">Profit generated by each actuary</p>
        <div className="w-10 h-px bg-violet-500 dark:bg-violet-400 mb-8" />

        {/* Sub-tab navigation */}
        <div className="flex border-b border-slate-200 dark:border-slate-700 mb-8">
          <NavLink to="/admin/bank-profit/actuaries" className={tabClass}>
            Actuary Performances
          </NavLink>
          <NavLink to="/admin/bank-profit/fund-positions" className={tabClass}>
            Fund Positions
          </NavLink>
        </div>

        {/* Table */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden">
          {loading ? (
            <div className="flex items-center justify-center py-16">
              <p className="text-slate-500 dark:text-slate-400 text-sm">Loading…</p>
            </div>
          ) : error ? (
            <div className="flex items-center justify-center py-16">
              <p className="text-red-500 text-sm">Failed to load actuary performances.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-slate-700">
                    <th className="px-4 py-4 text-left text-xs tracking-widest uppercase text-slate-500 dark:text-slate-400 font-medium">Name</th>
                    <th className="px-4 py-4 text-left text-xs tracking-widest uppercase text-slate-500 dark:text-slate-400 font-medium">Position</th>
                    <th
                      className="px-4 py-4 text-left text-xs tracking-widest uppercase text-slate-500 dark:text-slate-400 font-medium cursor-pointer select-none hover:text-slate-800 dark:hover:text-slate-200"
                      onClick={() => setSortAsc(v => !v)}
                    >
                      Profit (RSD) {sortAsc ? '↑' : '↓'}
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {sorted.length === 0 ? (
                    <tr>
                      <td colSpan={3} className="px-4 py-12 text-center text-slate-400 dark:text-slate-500 text-sm">
                        No actuary performance data available.
                      </td>
                    </tr>
                  ) : (
                    sorted.map((perf, i) => (
                      <tr
                        key={perf.id ?? i}
                        className={`border-b border-slate-100 dark:border-slate-800 last:border-0 ${
                          i % 2 !== 0 ? 'bg-slate-50/50 dark:bg-slate-800/20' : ''
                        }`}
                      >
                        <td className="px-4 py-3 text-slate-800 dark:text-slate-200 font-medium">
                          {perf.firstName} {perf.lastName}
                        </td>
                        <td className="px-4 py-3">
                          <span className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${POSITION_STYLES[perf.position] ?? POSITION_STYLES.ADMIN}`}>
                            {perf.position ?? '—'}
                          </span>
                        </td>
                        <td className={`px-4 py-3 font-medium tabular-nums ${
                          (perf.profit ?? 0) >= 0
                            ? 'text-emerald-600 dark:text-emerald-400'
                            : 'text-red-500 dark:text-red-400'
                        }`}>
                          {perf.profit != null ? fmt(perf.profit, 'RSD') : '—'}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          )}
          {!loading && !error && sorted.length > 0 && (
            <div className="px-4 py-3 border-t border-slate-100 dark:border-slate-800 text-xs text-slate-400 dark:text-slate-500">
              {sorted.length} actuar{sorted.length !== 1 ? 'ies' : 'y'}
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
